# Generated by Django 4.2.7 on 2023-11-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='first_name', max_length=100)),
                ('last_name', models.CharField(db_column='last_name', max_length=100)),
                ('tg_id', models.IntegerField(db_column='tg_id')),
                ('date_birth', models.DateField(db_column='birthday')),
            ],
            options={
                'db_table': 'TgUser',
            },
        ),
    ]
