# Generated by Django 4.2.7 on 2023-11-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_tguser_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='date_birth',
            field=models.DateTimeField(db_column='birthday'),
        ),
    ]
